server:
  port: 8081

spring:
    datasource:
       url: jdbc:postgresql://localhost:5432/minio_proj
       username: postgres
       password: 123


    jpa:
      database-platform: org.hibernate.dialect.PostgreSQLDialect
      database: POSTGRESQL
      hibernate:
       ddl-auto: update

minio:
  bucket:
    name: test
  default:
    folder: "/"
  access:
    name: minioadmin
    secret: minioadmin

    url: http://127.0.0.1:9000